FROM internetofvehicles/encoders

ADD https://raw.githubusercontent.com/internetofvehicles/ENCODERS/evaluation/haggle/resources/config-flood-direct.xml /home/ubuntu/.Haggle/config.xml
RUN ls -l && sudo chown -R ubuntu:ubuntu /home/ubuntu

